// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOpgHr6FT41edIxSEAgHtafCBOOO0df64',
    appId: '1:872265600127:web:154f75f779120a6bdfc34a',
    messagingSenderId: '872265600127',
    projectId: 'planery-exclusive-demo',
    authDomain: 'planery-exclusive-demo.firebaseapp.com',
    databaseURL: 'https://planery-exclusive-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planery-exclusive-demo.appspot.com',
    measurementId: 'G-7DY4LRQLHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7Lqkymimp_wlR8umGFoco5ijA5IdsM0',
    appId: '1:872265600127:android:f84ee199ae9edb99dfc34a',
    messagingSenderId: '872265600127',
    projectId: 'planery-exclusive-demo',
    databaseURL: 'https://planery-exclusive-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planery-exclusive-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuwzPnZUIkQqvyFne6a78593JRK1V6OAk',
    appId: '1:872265600127:ios:f2a9abf798e2594edfc34a',
    messagingSenderId: '872265600127',
    projectId: 'planery-exclusive-demo',
    databaseURL: 'https://planery-exclusive-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planery-exclusive-demo.appspot.com',
    iosClientId: '872265600127-k2qqch10h2mmth15lk7u3o1j2ptebov1.apps.googleusercontent.com',
    iosBundleId: 'com.example.planeryExclusiveDemoV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuwzPnZUIkQqvyFne6a78593JRK1V6OAk',
    appId: '1:872265600127:ios:f2a9abf798e2594edfc34a',
    messagingSenderId: '872265600127',
    projectId: 'planery-exclusive-demo',
    databaseURL: 'https://planery-exclusive-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planery-exclusive-demo.appspot.com',
    iosClientId: '872265600127-k2qqch10h2mmth15lk7u3o1j2ptebov1.apps.googleusercontent.com',
    iosBundleId: 'com.example.planeryExclusiveDemoV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOpgHr6FT41edIxSEAgHtafCBOOO0df64',
    appId: '1:872265600127:web:00b07835e95ec52ddfc34a',
    messagingSenderId: '872265600127',
    projectId: 'planery-exclusive-demo',
    authDomain: 'planery-exclusive-demo.firebaseapp.com',
    databaseURL: 'https://planery-exclusive-demo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'planery-exclusive-demo.appspot.com',
    measurementId: 'G-L2G69Z2XLV',
  );
}
